# Generated by Django 4.1.1 on 2022-09-16 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mismain', '0002_alter_department_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='createad',
            new_name='created',
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstnme', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('salary', models.FloatField()),
                ('doj', models.DateField()),
                ('address', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mismain.department')),
            ],
        ),
    ]
